### ISSUE TITLE
Monitoring is throwing an error

### ISSUE THREAD

**Issue by alex-stout** [UWEC-ITC/parkingNotifier-API#10]
```
> parkingnotifier-api@1.0.0 check-status /Users/alexstout/ITC/parkingNotifier-API
> node helpers/monitor.js

{ StatusCodeError: 500 - "\r\n<!DOCTYPE html>\r\n\r\n<html lang=\"en\">\r\n<head id=\"Head1\"><meta charset=\"UTF-8\" /><meta http-equiv=\"X-UA-Compatible\" content=\"IE=9; IE=8; IE=7; IE=EDGE\" /><title>\r\n\t\r\n    City of Eau Claire, Wisconsin | Home\r\n\r\n</title>"
    at new StatusCodeError (/Users/alexstout/ITC/parkingNotifier-API/node_modules/request-promise-core/lib/errors.js:32:15)
    at /Users/alexstout/ITC/parkingNotifier-API/node_modules/request-promise-core/lib/plumbing.js:97:41
    at tryCatcher (/Users/alexstout/ITC/parkingNotifier-API/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/Users/alexstout/ITC/parkingNotifier-API/node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (/Users/alexstout/ITC/parkingNotifier-API/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromiseCtx (/Users/alexstout/ITC/parkingNotifier-API/node_modules/bluebird/js/release/promise.js:606:10)
    at Async._drainQueue (/Users/alexstout/ITC/parkingNotifier-API/node_modules/bluebird/js/release/async.js:138:12)
    at Async._drainQueues (/Users/alexstout/ITC/parkingNotifier-API/node_modules/bluebird/js/release/async.js:143:10)
    at Immediate.Async.drainQueues (/Users/alexstout/ITC/parkingNotifier-API/node_modules/bluebird/js/release/async.js:17:14)
    at runCallback (timers.js:800:20)
    at tryOnImmediate (timers.js:762:5)
    at processImmediate [as _immediateCallback] (timers.js:733:5)
  name: 'StatusCodeError',
  statusCode: 500,
  message: '500 - "\\r\\n<!DOCTYPE html>\\r\\n\\r\\n<html lang=\\"en\\">\\r\\n<head id=\\"Head1\\"><meta charset=\\"UTF-8\\" /><meta http-equiv=\\"X-UA-Compatible\\" content=\\"IE=9; IE=8; IE=7; IE=EDGE\\" /><title>\\r\\n\\t\\r\\n    City of Eau Claire, Wisconsin | Home\\r\\n\\r\\n</title>"',
  error: '\r\n<!DOCTYPE html>\r\n\r\n<html lang="en">\r\n<head id="Head1"><meta charset="UTF-8" /><meta http-equiv="X-UA-Compatible" content="IE=9; IE=8; IE=7; IE=EDGE" /><title>\r\n\t\r\n    City of Eau Claire, Wisconsin | Home\r\n\r\n</title>',
  options: 
   { uri: 'http://www.ci.eau-claire.wi.us/',
     transform: [Function: transform],
     callback: [Function: RP$callback],
     simple: true,
     resolveWithFullResponse: false,
     transform2xxOnly: false },
  response: 
   { [Function: initialize]
     fn: initialize { constructor: [Circular], _originalRoot: [Object] },
     load: [Function],
     html: [Function],
     xml: [Function],
     text: [Function],
     parseHTML: [Function],
     root: [Function],
     contains: [Function],
     merge: [Function],
     _root: 
      { type: 'root',
        name: 'root',
        namespace: 'http://www.w3.org/1999/xhtml',
        attribs: {},
        'x-attribsNamespace': {},
        'x-attribsPrefix': {},
        children: [Array],
        parent: null,
        prev: null,
        next: null },
     _options: 
      { withDomLvl1: true,
        normalizeWhitespace: false,
        xml: false,
        decodeEntities: true } } }
```

**Comment by alex-stout** [comment]
![screen shot 2018-01-22 at 9 54 07 am](https://user-images.githubusercontent.com/17804548/35229911-3e1af366-ff5a-11e7-8ec1-4ea8f599e38f.png)

It looks like the website doesn't have the alert banner up yet. They do have the alternate side parking in the "Latest news" section though.

**Comment by alex-stout** [comment]
The banner is up now and it's still throwing the error.

**Comment by alex-stout** [comment]
Closing this for now.
